vim.g.mapleader = ' '
vim.g.maplocalleader = ','

require 'sebas.bootstrap-lazy-nvim'
require 'sebas.disable-builtins'
require 'sebas.options'
require 'sebas.keymaps'
require 'sebas.wiki'
require 'sebas.plugins'
require 'sebas.lsp'
