- name: >
    Load package config tasks for {{ ansible_distribution }} ({{ ansible_os_family }})

  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - default.yml
  tags: tasks
