{
  imports = [
    ./calibre.nix
    ./cross-compile.nix
    ./desktop.nix
    ./elastic-endpoint.nix
    ./embedded.nix
    ./home-manager.nix
    ./hyprland.nix
    ./laptop.nix
    ./nix-ld.nix
    ./ollama.nix
    ./quietboot.nix
    ./sensible.nix
    ./sway.nix
    ./syncthing.nix
    ./virtualisation.nix
    ./yubikey.nix
    ./zwift.nix
  ];
}
