- name: "Change default user shell to {{ default_shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ default_shell }}"
- name: "Configure groups for {{ user_name }}"
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ system_groups }}"
    append: true
- name: "Configure systemd services"
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop: "{{ systemd_services }}"
  notify:
    - Start systemd services
- name: "Configure systemd services in userspace"
  become: false
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    scope: "user"
  loop: "{{ systemd_services_userspace }}"
  when: systemd_services_userspace is defined
  notify:
    - Start systemd services at userspace
- name: >
    Load system config tasks for {{ ansible_distribution }} ({{ ansible_os_family }})

  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - default.yml
  tags: tasks
- name: Configure udev rules for USB wakeup devices
  ansible.builtin.template:
    src: udev/90-usbwakeup.rules
    dest: /etc/udev/rules.d/
    mode: "0644"
  when: wakeup_devices is defined
- name: Disable wakeup using Lid
  ansible.builtin.template:
    src: systemd/disable-lid.conf
    dest: "/etc/tmpfiles.d/disable-{{ lid_name }}.conf"
    mode: "0644"
  when: lid_name is defined
- name: Enable WoL
  ansible.builtin.template:
    src: systemd/wol@.service
    dest: /etc/systemd/system/wol@.service
    mode: "0644"
- name: Enable FastConnectable blueetooth feature
  ansible.builtin.template:
    src: bluetooth/main.conf
    dest: /etc/bluetooth/main.conf
    mode: "0644"
# workaround to make swaync works, it expects this file at startup
# but since the package is installed using home-manager, the file does not exist
- name: Create swaync global config directory
  ansible.builtin.file:
    path: /etc/xdg/swaync
    state: directory
    mode: "0755"
    recurse: true
    modification_time: preserve
    access_time: preserve
- name: Set swaync global fallback style
  ansible.builtin.file:
    path: /etc/xdg/swaync/style.css
    state: touch
    mode: "0644"
    modification_time: preserve
    access_time: preserve
