---
- name: "Change default user shell to {{ default_shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ default_shell }}"

- name: "Set groups for {{ distro.family }}"
  ansible.builtin.set_fact:
    system_groups: >
      {{
        system_groups[distro.family] | default([])
      }}

- name: "Configure groups for {{ user_name }}"
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ system_groups }}"
    append: true

- name: "Set systemd services to enable for {{ distro.family }}"
  ansible.builtin.set_fact:
    systemd_services: >
      {{
        systemd_services[distro.family] | default([])
      }}

- name: "Configure systemd services"
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop: "{{ systemd_services }}"
  notify: 
    - Start systemd services

