---
- name: "Change default user shell to {{ default_shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: "{{ default_shell }}"

- name: "Configure groups for {{ user_name }}"
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ system_groups }}"
    append: true

- name: "Configure systemd services"
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop: "{{ systemd_services }}"
  notify:
    - Start systemd services
