[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cliphist-to-wofi"
version = "0.1.0"
description = ""
authors = [{ name = "Sebastián Zaffarano", email = "sebas@zaffarano.com.ar" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cliphist-to-wofi = "cliphist:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cliphist"]
