[[profile]]
name = "docked-home-sw"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = false
search = ["m=0x152E", "v=Chimei Innolux Corporation"]

[[profile.output]]
enable = true
search = ["m=LG HDR 4K", "s=301MAPNGQZ84", "v=LG Electronics"]
mode = "2560x1440"
position = "0,0"
scale = 1.0

[[profile.output]]
enable = false
search = ["m=ASUS VA24E", "s=LBLMTF309577", "v=ASUSTek COMPUTER INC"]

[[profile]]
name = "undocked-sw"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=0x152E", "v=Chimei Innolux Corporation"]
mode = "best"
position = "0,0"
scale = 1.0

[[profile]]
name = "docked-home-cb"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = false
search = ["m=0x14E5", "v=Chimei Innolux Corporation"]

[[profile.output]]
enable = true
search = ["m=LG HDR 4K", "s=301MAPNGQZ84", "v=LG Electronics"]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0

[[profile]]
name = "undocked-cb"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=0x14E5", "s=", "v=Chimei Innolux Corporation"]
mode = "best"
position = "0,0"
scale = 1.0

[[profile]]
name = "docked-ba"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = false
search = ["m=0x152E", "v=Chimei Innolux Corporation"]

[[profile.output]]
enable = true
search = ["m=23MP55", "s=0x00001748", "v=LG Electronics"]
mode = "1920x1080@59.94Hz"
position = "0,0"
scale = 1.0

[[profile]]
name = "docked-home-dual"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]

[[profile.output]]
enable = true
search = ["m=LG HDR 4K", "s=301MAPNGQZ84", "v=LG Electronics"]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0

[[profile.output]]
enable = false
search = ["m=0x152E", "s=", "v=Chimei Innolux Corporation"]

[[profile.output]]
enable = true
search = ["m=ASUS VA24E", "s=LBLMTF309577", "v=ASUSTek COMPUTER INC"]
mode = "1920x1080@74.986Hz"
position = "2560,0"
scale = 1.0
