#!/usr/bin/env bash

set -euo pipefail

BASEDIR="$(realpath "$(dirname "$0")"/..)"

pushd "$BASEDIR" > /dev/null
home-manager switch --flake . \
  && systemctl --user restart \
    copyq.service \
    fluidsynth.service \
    gammastep.service \
    kanshi.service \
    network-manager-applet.service \
    pasystray.service \
    playerctld.service \
    swayidle.service \
    syncthing.service \
    waybar.service \
    xsettingsd.service
popd > /dev/null
