#!/usr/bin/env bash

set -euo pipefail

BASEDIR="$(realpath "$(dirname "$0")"/..)"
NVIM_CONFIG="$XDG_CONFIG_HOME"/nvim
CACHIX_PREFIX="cachix watch-exec szaffarano --"

if [ -n "${DISABLE_CACHIX_PUSH:-}" ]; then
  echo "Cachix push disabled"
  CACHIX_PREFIX=""
fi

[ -L "$NVIM_CONFIG" ] && rm "$NVIM_CONFIG"

pushd "$BASEDIR" >/dev/null
$CACHIX_PREFIX home-manager switch --flake .
popd >/dev/null
