#!/usr/bin/env bash

set -euo pipefail

BASEDIR="$(realpath "$(dirname "$0")"/..)"
CACHIX_PREFIX="cachix watch-exec szaffarano --"

if [ -n "${DISABLE_CACHIX_PUSH:-}" ]; then
  echo "Cachix push disabled"
  CACHIX_PREFIX=""
fi

pushd "$BASEDIR" >/dev/null
$CACHIX_PREFIX sudo nixos-rebuild switch --flake .
popd >/dev/null
