---
- name: Setup Linux Workstation
  gather_facts: true
  become: true
  hosts: all
  vars:
    ansible_connection: local
  pre_tasks:
    - name: Load common variables
      ansible.builtin.include_vars:
        file: all.yml

    - name: Load a variable file based on the OS type
      ansible.builtin.include_vars: >
        "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - '{{ansible_distribution}}.yml'
            - '{{ansible_os_family}}.yml'
            - default.yml
          paths:
            - vars
  roles:
    - packages
    - system
    - geerlingguy.docker
